version: '3.8'

volumes:
  db:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db:/var/lib/postgresql/data"
  app:
    build: .
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public